apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
spec:
  selector:
    matchLabels:
      app: golang-api
  replicas: 3
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: xvndex/task1docker
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: golang-api
spec:
  selector:
    app: golang-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 9376